version: '3'
services:
  db:
    image: "postgres:latest"
    container_name: "ccca_course_pg"
    volumes:
      - ./database/dump.sql:/dump.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
networks:
  api-network:
      driver: bridge

